name: Debug token
on:
  push:
    paths:
      - '.github/workflows/debug-token.yml'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sI -H "Authorization: token ${{ secrets.WINGET_TOKEN }}" https://api.github.com/user | grep -iE "^HTTP|x-oauth-scopes"
